database:
  server: SPWS-VM-DB81
  database: OdsCorp
  driver: SQL Server
  auth_type: windows # ou 'sql' se for usar user/pass
  user: null
  password: null

data:
  raw_path: data/raw/raw_history.csv
  clean_path: data/interim/clean_data.csv
  processed_train_path: data/processed/train_data.csv
  processed_future_path: data/processed/future_data.csv # Dados para predição
  janela_dias: 120 # Janela de treino em dias
  data_corte_final: null # Opcional: Data de corte no formato DD/MM/YYYY (ex: '31/01/2026'). Se null, usa data atual.
  
  target: NS_Real # Variável Alvo (calculada no preprocessing: Vol_Atendidas_NS_Real / Vol_Real)
  features:
    # --- METAS (Dados Disponíveis antes do Fato) ---
    - Vol_Previsto
    - HC_Previsto
    - Tempo_AHT_Previsto_Total
    
    # --- CONTEXTO TEMPORAL (Padrões Sazonais) ---
    - Hora
    - DiaSemana
    
    # --- INDICADORES DE RH / QUALIDADE (Modelo GO!) ---
    - ABS_Taxa_Daily
    - Turnover_Taxa_Daily
    - Ferias_Qtd_Daily
    - Faltas_Qtd_Daily
    - WAHA_Qtd_Daily
    
    # --- SINAIS DE FUMAÇA (Lags: O que estava acontecendo 30-90 minutos atrás) ---
    - NS_Lag_1
    - NS_Lag_2
    - NS_Lag_3
    - Taxa_Abandono_Lag_1
    
    # --- EFICIÊNCIA, OCUPAÇÃO E DESVIOS (Lags: Imediato Passado D-1) ---
    - TME_Real_Avg_Lag_1
    - Taxa_Ocupacao_Lag_1
    - Taxa_Pausa_Tecnica_Lag_1
    - Taxa_Pausa_Pessoal_Lag_1
    - Taxa_Pausa_Gestao_Lag_1
    - Desvio_HC_Pct_Lag_1
    - Desvio_Volume_Pct_Lag_1

model:
  path: models/model.pkl
  metrics_path: metrics/train_metrics.json
  type: XGBRegressor # XGBoost - Mais indicado para Tabular/Deltas
  training:
    sample_threshold: 500000
    sample_frac: 0.2
  params:
    n_estimators: 100
    max_depth: 5
    learning_rate: 0.1
    random_state: 42
    n_jobs: -1

inference:
  output_path: data/processed/predictions.csv
