digest: 20364bd0
name: dataset
profile: '{"features_shape": [391, 33], "features_size": 12903, "features_nbytes":
  51612}'
schema: '{"mlflow_tensorspec": {"features": "[{\"type\": \"tensor\", \"tensor-spec\":
  {\"dtype\": \"float32\", \"shape\": [-1, 33]}}]", "targets": null}}'
source: '{"tags": {"mlflow.user": "DANI", "mlflow.source.name": "src\\model_training\\train_model.py",
  "mlflow.source.type": "LOCAL", "mlflow.source.git.commit": "c0c67e133653c946f4d12360d69155fcb91cecb1"}}'
source_type: code
