artifact_location: file:///C:/TP_ML/BI_Ferramenta_Correlacao_Inteligente/SmartCorr/mlruns/167264636866618085
creation_time: 1776105189952
experiment_id: '167264636866618085'
last_update_time: 1776105189952
lifecycle_stage: active
name: ml_regression
