digest: 14121ec2
name: dataset
profile: '{"features_shape": [585, 20], "features_size": 11700, "features_nbytes":
  46800}'
schema: '{"mlflow_tensorspec": {"features": "[{\"type\": \"tensor\", \"tensor-spec\":
  {\"dtype\": \"float32\", \"shape\": [-1, 20]}}]", "targets": null}}'
source: '{"tags": {"mlflow.user": "DANI", "mlflow.source.name": "main.py", "mlflow.source.type":
  "LOCAL", "mlflow.source.git.commit": "c0c67e133653c946f4d12360d69155fcb91cecb1"}}'
source_type: code
