artifact_uri: file:///C:/TP_ML/BI_Ferramenta_Correlacao_Inteligente/SmartCorr/mlruns/167264636866618085/fd01ce2ad4b14412a58b22fe6ec0e50d/artifacts
end_time: 1776898359313
entry_point_name: ''
experiment_id: '167264636866618085'
lifecycle_stage: active
run_id: fd01ce2ad4b14412a58b22fe6ec0e50d
run_name: programa_347851
source_name: ''
source_type: 4
source_version: ''
start_time: 1776898242918
status: 3
tags: []
user_id: DANI
