digest: 5eae3376
name: validation_0
profile: '{"features_shape": [146, 27], "features_size": 3942, "features_nbytes":
  15768}'
schema: '{"mlflow_tensorspec": {"features": "[{\"type\": \"tensor\", \"tensor-spec\":
  {\"dtype\": \"float32\", \"shape\": [-1, 27]}}]", "targets": null}}'
source: '{"tags": {"mlflow.user": "DANI", "mlflow.source.name": "C:\\TP_ML\\BI_Ferramenta_Correlacao_Inteligente\\SmartCorr\\src\\model_training\\train_model.py",
  "mlflow.source.type": "LOCAL", "mlflow.source.git.commit": "c0c67e133653c946f4d12360d69155fcb91cecb1"}}'
source_type: code
