digest: f0893a23
name: dataset
profile: '{"features_shape": [8958, 30], "features_size": 268740, "features_nbytes":
  1074960}'
schema: '{"mlflow_tensorspec": {"features": "[{\"type\": \"tensor\", \"tensor-spec\":
  {\"dtype\": \"float32\", \"shape\": [-1, 30]}}]", "targets": null}}'
source: '{"tags": {"mlflow.user": "DANI", "mlflow.source.name": "C:\\TP_ML\\BI_Ferramenta_Correlacao_Inteligente\\SmartCorr\\src\\model_training\\train_model.py",
  "mlflow.source.type": "LOCAL", "mlflow.source.git.commit": "dafc6c237c5ffa3e5f4d9b5990a53f2ac4a28cc4"}}'
source_type: code
