artifact_location: file:///C:/TP_ML/BI_Ferramenta_Correlacao_Inteligente/SmartCorr/mlruns/0
creation_time: 1776105189896
experiment_id: '0'
last_update_time: 1776105189896
lifecycle_stage: active
name: Default
