artifact_uri: file:///C:/TP_ML/BI_Ferramenta_Correlacao_Inteligente/SmartCorr/mlruns/167264636866618085/b454eba92612439ca5dcd8df8bb0fdfb/artifacts
end_time: 1776719161339
entry_point_name: ''
experiment_id: '167264636866618085'
lifecycle_stage: active
run_id: b454eba92612439ca5dcd8df8bb0fdfb
run_name: programa_589361
run_uuid: b454eba92612439ca5dcd8df8bb0fdfb
source_name: ''
source_type: 4
source_version: ''
start_time: 1776718964970
status: 3
tags: []
user_id: DANI
