digest: 79c382c1
name: dataset
profile: '{"num_rows": 9058, "num_elements": 271740}'
schema: '{"mlflow_colspec": [{"type": "double", "name": "Vol_Previsto", "required":
  true}, {"type": "double", "name": "HC_Previsto", "required": true}, {"type": "double",
  "name": "Tempo_AHT_Previsto_Total", "required": true}, {"type": "long", "name":
  "Hora", "required": true}, {"type": "long", "name": "DiaSemana", "required": true},
  {"type": "double", "name": "ABS_Taxa_Daily", "required": true}, {"type": "double",
  "name": "Turnover_Taxa_Daily", "required": true}, {"type": "long", "name": "Ferias_Qtd_Daily",
  "required": true}, {"type": "long", "name": "Faltas_Qtd_Daily", "required": true},
  {"type": "long", "name": "WAHA_Qtd_Daily", "required": true}, {"type": "double",
  "name": "Taxa_Abandono_Lag_1", "required": true}, {"type": "double", "name": "TME_Real_Avg_Lag_1",
  "required": true}, {"type": "double", "name": "Taxa_Ocupacao_Lag_1", "required":
  true}, {"type": "double", "name": "Taxa_Pausa_Tecnica_Lag_1", "required": true},
  {"type": "double", "name": "Taxa_Pausa_Pessoal_Lag_1", "required": true}, {"type":
  "double", "name": "Taxa_Pausa_Gestao_Lag_1", "required": true}, {"type": "double",
  "name": "Desvio_HC_Pct_Lag_1", "required": true}, {"type": "double", "name": "Desvio_Volume_Pct_Lag_1",
  "required": true}, {"type": "double", "name": "Delta_TMA_Lag_1", "required": true},
  {"type": "double", "name": "Pressao_Prevista_Vol_HC", "required": true}, {"type":
  "double", "name": "Indicador_Sufoco", "required": true}, {"type": "double", "name":
  "Vol_Por_Agente", "required": true}, {"type": "double", "name": "Margem_Capacidade",
  "required": true}, {"type": "double", "name": "Desvio_Escala_Pct", "required": true},
  {"type": "double", "name": "Razao_Escala", "required": true}, {"type": "double",
  "name": "Taxa_Sobrecarga", "required": true}, {"type": "double", "name": "PerdaLog_Taxa_Daily",
  "required": true}, {"type": "double", "name": "TechIssues_Taxa_Daily", "required":
  true}, {"type": "double", "name": "NewHire_Pct_Daily", "required": true}, {"type":
  "double", "name": "AgentIssues_Taxa_Daily", "required": true}]}'
source: '{"tags": {"mlflow.user": "DANI", "mlflow.source.name": "C:\\TP_ML\\BI_Ferramenta_Correlacao_Inteligente\\SmartCorr\\src\\model_training\\train_model.py",
  "mlflow.source.type": "LOCAL", "mlflow.source.git.commit": "dafc6c237c5ffa3e5f4d9b5990a53f2ac4a28cc4"}}'
source_type: code
